---
title: "Unpopular norms"
bibliography: references.bib
link-citations: true
output: 
  html_document:
    css: tweaks.css
    toc:  false
    toc_float: true
    number_sections: false
    code_download: false
    
---


```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()

colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```


----

# **The emergence of an unpopular norm in a social network experiment**

#### [Rob Franken](https://robfranken.github.io/) - Utrecht University
#### [Rense Corten](https://www.uu.nl/staff/RCorten) - Utrecht University


Last compiled on `r format(Sys.time(), '%d-%m-%Y')`

----


This is a companion website to the paper of @Franken2025. It contains R code. All scripts can be found on [Github](https://github.com/robfranken/unpopular_norms).

Use the top menu to navigate through the sections.


----

## Contact  

Questions can be addressed to [Rob Franken](mailto:r.j.f.franken@uu.nl).
  
----

## References






